// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqwzetfrunmggojojita.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxd3pldGZydW5tZ2dvam9qaXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNjEyMDgsImV4cCI6MjA2NDgzNzIwOH0.rD9OdtoyxXIC_wIGOalSMzkKmcsV0_ccc6Rq7Y1z_rE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);